server:
  port: 8090
# spring setting
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://120.48.55.43:3306/springbootcli?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: psp128_master9515!
    driver-class-name: com.mysql.jdbc.Driver

# ====================MybatisPlus====================
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
      refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false