# spring setting
spring:
  profiles:
    active: mac
  application:
    name: educationadminsystem
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #springboot2.6及其以上版本需要设置以上
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://120.48.55.43:3306/eas?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: psp128_master9515!
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 120.48.55.43
    port: 6379
    password: master123456!
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

# ====================MybatisPlus====================
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
      refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

###
# 日志存放
logging:
  #path: /var/logs/${spring.application.name}
  level:
    com.tyy.springbootcli.mapper: DEBUG
    root: info
    org.springframework.web: info
  config: classpath:logback-spring.xml

knife4j:
  enable: true
